#! /usr/bin/guile -s
!#

(define lt (lambda (x)
	     (lambda (y)
	       (<= x y))))
(define gt (lambda (x)
	     (lambda (y)
	       (>= x y))))
(define eq (lambda (x)
	     (lambda (y)
	       (= x y))))
(define nil '())
(define filter (lambda (f l)
		 (if (null? l)
		     l
		     (if (f (car l))
			 (cons (car l)
			       (filter f (cdr l)))
			 (filter f (cdr l))))))
(define (p1 x) (+ 1 x))
(define (m1 x) (- x 1))

(define (safe-append x y z)
  (if (and (< (length x) 100)
	   (< (length y) 100)
	   (< (length z) 100))
      (append x y z)
      (throw 'deep)))

(define spend (let ((invocations 0))
		(lambda ()
		  (set! invocations (+ 1 invocations))
		  (if (= invocations 100)
		      (throw 'deep)))))

(define argument (call-with-input-string (caddr (command-line))
					 read))
(define body (call-with-input-string (cadr (command-line))
				     read))
(write (catch 'deep
	      (lambda () 
		(eval
		 `(letrec ((recur (lambda (a)
				    (spend)
				    ,body)))
		    (recur ,argument))
		 (interaction-environment)))
	      (lambda (e) 'bottom)))
(newline)
